name: Build & Deploy Backend

on:
  push:
    branches: ["master"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - run: |
          cd zarnab-panel-parent
          mvn -B package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: zarnab-application/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./artifact

      - name: Copy artifact to Hetzner
        run: |
          scp -i ${{ secrets.SSH_KEY }} -o StrictHostKeyChecking=no ./artifact/*.jar deploy@${{ vars.SSH_HOST }}:/var/www/zarnab/backend/artifact/

      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/zarnab/backend
            git pull origin master
            docker compose build
            docker compose up -d --remove-orphans
            docker image prune -f
