name: Build & Deploy Backend

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build backend locally
        run: |
          cd zarnab-panel-parent
          mvn -B package -DskipTests
          
          # Move the jar
          mkdir -p /var/www/zarnab/backend/zarnab-application/target/
          cp ../zarnab-application/target/*.jar /var/www/zarnab/backend/zarnab-application/target/app.jar

      - name: Docker Deploy
        run: |
          cd /var/www/zarnab/backend
          git config --global --add safe.directory /var/www/zarnab/backend
          # No need to pull if checkout worked, but safe to keep:
          git pull origin master 

          cd docker-compose/dev
          docker compose down redis
          docker compose build
          docker compose up -d --remove-orphans
          docker image prune -f