name: Build & Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar-path: ${{ steps.build-backend.outputs.jar-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        id: build-backend
        run: |
          cd zarnab-panel-parent
          mvn -B package -DskipTests
          echo "jar-path=target/*.jar" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: zarnab-panel-parent/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: ./artifact

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/zarnab/backend
            # Copy artifact to server
            mkdir -p ./artifact
            echo "${{ github.workspace }}/artifact/*.jar"
            # Example: use scp to copy jar if needed
            # scp ./artifact/*.jar deploy@${{ vars.SSH_HOST }}:/var/www/zarnab/backend/
            docker compose build
            docker compose up -d --remove-orphans
