name: Build & Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend (skip tests)
        run: |
          cd zarnab-panel-parent
          mvn -B package -DskipTests

      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/zarnab/backend
            git pull origin master
            docker compose build
            docker compose up -d --remove-orphans
            docker image prune -f
