name: Backend CI

on:
  pull_request:
    branches: [ "master" ]
#    paths:
#      - "zarnab-application/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build backend (skip tests)
        run: |
          cd zarnab-panel-parent
          ./mvnw -B package -DskipTests
